version: '3'
services:
  node:
    build: ./
    ports:
      - "80:80"
    volumes:
      - "./src:/home/aicon/editor/src"
      - "./data:/home/aicon/editor/data"
    pid: "host"
    command: node src/index.js